site_name: Hydraulic Conveyor
site_description: User guide for the Conveyor packaging tool.
site_url: https://conveyor.hydraulic.dev

extra:
  homepage: https://www.hydraulic.software
  version:
    provider: mike
  generator: false

nav:
  - Welcome:
    - Getting started: index.md
    - download-conveyor.md
    - keys-and-certificates.md
    - outputs.md
    - running.md
    - continuous-integration.md
    - release-notes.md
    - known-issues.md
  - Tutorial:
    - tutorial/1-get-started.md
    - tutorial/2-create-a-template-project.md
    - tutorial/3-compile.md
    - tutorial/4-build-unpackaged.md
    - tutorial/5-serve-the-site.md
    - tutorial/6-install-the-app.md
    - tutorial/7-release-an-update.md
    - tutorial/8-explore-the-integration.md
    - tutorial/9-site.md
    - tutorial/10-next-steps.md
  - Configuration:
    - configs/index.md
    - configs/inputs.md
    - configs/jvm.md
    - configs/electron.md
    - configs/linux.md
    - configs/mac.md
    - configs/windows.md
    - configs/native-apps.md
    - Download pages: configs/download-pages.md
    - HOCON:
        - Specification: configs/hocon-spec.md
        - Extensions: configs/hocon-extensions.md
        - Syncing with Maven and Gradle: configs/maven-gradle.md
    - Standard Library:
      - Index: stdlib/index.md
      - stdlib/jdks.md
      - stdlib/jvm-clients.md
      - stdlib/systemd.md
      - stdlib/javafx.md
  - Tasks:
      - tasks/index.md
      - tasks/server.md
      - tasks/jetpack-compose-desktop.md
      - tasks/swt.md
      - tasks/javafx.md
  - FAQ:
    - faq/index.md
    - faq/output-formats.md
    - faq/making-packages.md
    - faq/signing-and-certificates.md
    - Tips and troubleshooting: tips-and-troubleshooting.md

theme:
  name: 'material'
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - content.code.annotate
    - content.tabs.link

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: hydraulic
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode

  logo: 'images/logo-white.svg'
  favicon: images/favicon.ico

  font:
    text: Titillium Web
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - search

extra_css:
  - stylesheets/guidebook.css

extra_javascript:
  - javascripts/tasklist.js
